
ALTER TABLE Car
ADD CONSTRAINT FK_Car_Customer
FOREIGN KEY (id_customer) REFERENCES Customer(id)
ON DELETE CASCADE;

ALTER TABLE Car
ADD CONSTRAINT FK_Car_Car_Type
FOREIGN KEY (brand) REFERENCES Car_Type(id)
ON DELETE CASCADE;


ALTER TABLE Reservation
ADD CONSTRAINT FK_Reservation_Parking
FOREIGN KEY (parking_id) REFERENCES Parking(id)
ON DELETE CASCADE;

ALTER TABLE Reservation
ADD CONSTRAINT FK_Reservation_Car
FOREIGN KEY (car_id) REFERENCES Car(id)
ON DELETE CASCADE;
